# Generated by Django 3.2.12 on 2022-11-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_fees', models.CharField(max_length=150, unique=True)),
                ('member_coinsurance', models.CharField(blank=True, max_length=255, null=True)),
                ('member_copay', models.CharField(blank=True, max_length=20, null=True)),
                ('allowed_fees', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
