# Generated by Django 3.2.12 on 2022-11-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_claims'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
