# Generated by Django 3.2.12 on 2022-11-09 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claims_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
