# Generated by Django 3.2.12 on 2022-11-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_auto_20221109_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='./claims/'),
        ),
    ]
