# Generated by Django 3.2.12 on 2022-11-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_claim_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='./uploads/'),
        ),
    ]
