# Generated by Django 3.2.12 on 2022-11-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='provider_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
